version: '3'

services:
    
    app:
        build: .
        
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py runserver --insecure 0.0.0.0:8000"
