# Generated by Django 3.1.7 on 2021-04-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['intent'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('intents', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.intents')),
            ],
            options={
                'ordering': ['intents'],
            },
        ),
        migrations.CreateModel(
            name='Intent_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EN_Answer', models.TextField()),
                ('FR_Answer', models.TextField()),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.intents')),
            ],
            options={
                'ordering': ['intent'],
            },
        ),
    ]
