# Generated by Django 3.1.7 on 2021-04-26 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_msg_en', models.TextField()),
                ('greeting_msg_fr', models.TextField()),
                ('apology_msg', models.TextField()),
                ('default_fallback_msg', models.TextField()),
                ('misclassify_threshold', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='intent_answers',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.intents', unique=True),
        ),
        migrations.AlterField(
            model_name='intents',
            name='intent',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
