# Generated by Django 3.1.7 on 2021-04-26 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210426_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='misclassify_threshold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
