# Generated by Django 3.1.7 on 2021-04-27 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210426_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='misclassify_threshold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
