# Generated by Django 3.1.7 on 2021-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210427_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables',
            name='apology_msg',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='default_fallback_msg',
        ),
        migrations.AddField(
            model_name='variables',
            name='apology_msg_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='apology_msg_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='default_fallback_msg_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='default_fallback_msg_fr',
            field=models.TextField(null=True),
        ),
    ]
